name: Getting started

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "Building..."
  
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing...."
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying...."
      - run: sleep 60
      - run: echo "Successfully deployed...."

      - uses: actions/checkout@v2

      - run: mkdir -p path/to/artifact

      - run: echo hello > path/to/artifact/world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: path/to/artifact/world.txt
